language: python
python:
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy3"
install:
  - ./setup.py develop
  - pip install pytest pytest-cov
script:
  - py.test --cov=rusty_types --cov-report term-missing tests/
